---

- hosts: localhost
  connection: local
  gather_facts: False
  become: False
  tasks:
    - include_tasks: ec2-dynamic-inventory.yml
​
- hosts: mongodb

    - name: Set Facts
      set_fact:
        db_bkp_file_name: "{{ db_name }}-{{ lookup('pipe','date +%Y%m%d%H%M%p') }}.sql.gz"
        db_bkp_file_path_remote: "/tmp/{{ db_bkp_file_name }}"
        db_bkp_file_path_local: "/tmp/{{ ansible_fqdn }}/{{ db_bkp_file_name }}"

    - name: Delete existing backup file if present
      file:
        path: ​"{{ db_bkp_file_path_remote }}"
        state: absent

    - name: Generate database dump
      shell: |
          /bin/mongodump -u {{ db_user }} -p {{ dbpsw }} --archive={{ db_bkp_file_path_remote }} --gzip --db {{ dbname }}  # for specific
          #/bin/mongodump -u {{ db_user }} -p {{ dbpsw }} --archive={{ db_bkp_file_path_remote }} --gzip  # this for all db dumps
      vars:
        dbusr: "{{ db_user }}"
        dbpsw: "{{ db_psw }}"
        dbname: "{{ db_name }}"
      run_once: true

    # fetch file to localhost
    - name: Fetch backup file to localhost
      fetch:
        src: "{{ db_bkp_file_path_remote }}"
        dest: "{{ db_bkp_file_path_local }}"
        fail_on_missing: yes
        flat: yes # do not preserve path

    # upload backup file to S3
    - name: Push the generated backup file {{ db_bkp_file_path_local }} to S3
      aws_s3:
        aws_access_key: "{{ hostvars['localhost']['AWS_ACCESS_KEY'] }}"
        aws_secret_key: "{{ hostvars['localhost']['AWS_SECRET_KEY'] }}"
        security_token: "{{ hostvars['localhost']['AWS_SECURITY_TOKEN'] }}"
        mode: put
        bucket: "{{ s3_bucket }}"
        object: "/dbbackups/{{ instanceEnv }}/{{ db_bkp_file_name }}"
        src: "{{ db_bkp_file_path_local }}"
        overwrite: different
      delegate_to: localhost
  ​
    - name: Delete tmp file {{ db_bkp_file_path_local }} from local file system
      file:
        path: "{{ db_bkp_file_path_local }}"
        state: absent
      delegate_to: localhost

## End
